/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSubscribersRouteImport } from './routes/_app/subscribers'
import { Route as AppMailboxesRouteImport } from './routes/_app/mailboxes'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns/index'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/_app/campaigns/$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AppRoute,
} as any)
const AppMailboxesRoute = AppMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/logs': typeof AppLogsRoute
  '/mailboxes': typeof AppMailboxesRoute
  '/subscribers': typeof AppSubscribersRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logs': typeof AppLogsRoute
  '/mailboxes': typeof AppMailboxesRoute
  '/subscribers': typeof AppSubscribersRoute
  '/': typeof AppIndexRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/campaigns': typeof AppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/mailboxes': typeof AppMailboxesRoute
  '/_app/subscribers': typeof AppSubscribersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logs'
    | '/mailboxes'
    | '/subscribers'
    | '/campaigns/$campaignId'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logs'
    | '/mailboxes'
    | '/subscribers'
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/logs'
    | '/_app/mailboxes'
    | '/_app/subscribers'
    | '/_app/'
    | '/_app/campaigns/$campaignId'
    | '/_app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers': {
      id: '/_app/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mailboxes': {
      id: '/_app/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AppMailboxesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$campaignId': {
      id: '/_app/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLogsRoute: typeof AppLogsRoute
  AppMailboxesRoute: typeof AppMailboxesRoute
  AppSubscribersRoute: typeof AppSubscribersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLogsRoute: AppLogsRoute,
  AppMailboxesRoute: AppMailboxesRoute,
  AppSubscribersRoute: AppSubscribersRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
