"""add campaign pause_reason

Revision ID: 04180223016f
Revises: 2f19ff96835c
Create Date: 2026-07-11 14:32:44.771229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04180223016f'
down_revision: Union[str, Sequence[str], None] = '2f19ff96835c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('pause_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'pause_reason')
    # ### end Alembic commands ###
