"""drop subscriber source_site, audiences are shared across sites

Revision ID: 1773ce559437
Revises: 04180223016f
Create Date: 2026-07-11 21:27:20.282257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1773ce559437'
down_revision: Union[str, Sequence[str], None] = '04180223016f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'source_site')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('source_site', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
