"""add tracked_links, click_events, open_events

Revision ID: 2f19ff96835c
Revises: e29731434399
Create Date: 2026-07-11 14:18:09.897122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f19ff96835c'
down_revision: Union[str, Sequence[str], None] = 'e29731434399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('send_event_id', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['send_event_id'], ['send_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('send_event_id', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['send_event_id'], ['send_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('click_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracked_link_id', sa.String(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_link_id'], ['tracked_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_events')
    op.drop_table('tracked_links')
    op.drop_table('open_events')
    # ### end Alembic commands ###
