"""make send_event mailbox_id nullable

Revision ID: e29731434399
Revises: 0482214f3672
Create Date: 2026-07-11 13:40:48.694956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29731434399'
down_revision: Union[str, Sequence[str], None] = '0482214f3672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('send_events', 'mailbox_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('send_events', 'mailbox_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
